ARG UBUNTU_VERSION=20.04
FROM ubuntu:${UBUNTU_VERSION} AS builder

RUN apt-get update && apt-get install -y git sudo make ruby bundler python3 python3-pip build-essential zip python3-venv

RUN mkdir -p /app
WORKDIR /app

COPY ./src/bxfzip.py /app/bxfzip.py
COPY ./src/requirements.txt /app/requirements.txt

RUN python3 -m venv /app/venv \
    && . /app/venv/bin/activate \
    && pip install -r requirements.txt \
    && pyinstaller --onefile bxfzip.py --distpath /app/dist
